apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secure-api-config
  namespace: secure-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: secure-api-config
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secure-api/dev/database-url
