apiVersion: v1
kind: Namespace
metadata:
  name: secure-app
  labels:
    app.kubernetes.io/managed-by: gitops
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
